#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y update
apt-get install -y haproxy


 # Listen to web1 and web2 servers 
echo "
frontend http_front
	bind *0:80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 806521-web-01 52.3.243.24:80 check
	server 806521-web-02 52.87.13.19:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
