#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".

n=0
while [ $n -lt 10 ];
do
	if [ $n -eq 9 ];then
		echo "Hi"
	fi
	echo "Best School"
	((n++))
done
