#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 5

n=0
while [ $n -le 12 ];
do
	echo "Hour: $n"

	j=1
	while [ $j -lt 60 ];
	do
		echo $j
		((j++))
	done
	((n++))
done
