#!/usr/bin/env/bash
# fix issues rising from using docker
# make apache server return Hello Alx when querying tje root

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello ALX" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
