#!/usr/bin/env bash
# Change user and listening port
sed -i 's/^user .*/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo service nginx restart
